[2023-07-24 08:28:42,187] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_final_project.get_data_from_api scheduled__2023-07-23T00:00:00+00:00 [queued]>
[2023-07-24 08:28:42,201] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_final_project.get_data_from_api scheduled__2023-07-23T00:00:00+00:00 [queued]>
[2023-07-24 08:28:42,201] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 08:28:42,202] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-24 08:28:42,203] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 08:28:42,232] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_from_api> on 2023-07-23 00:00:00+00:00
[2023-07-24 08:28:42,238] {standard_task_runner.py:52} INFO - Started process 211 to run task
[2023-07-24 08:28:42,242] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_final_project', 'get_data_from_api', 'scheduled__2023-07-23T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/d_1_final_project.py', '--cfg-path', '/tmp/tmprr_4pc5n', '--error-file', '/tmp/tmpqxc6efml']
[2023-07-24 08:28:42,244] {standard_task_runner.py:80} INFO - Job 12: Subtask get_data_from_api
[2023-07-24 08:28:42,330] {task_command.py:369} INFO - Running <TaskInstance: d_1_final_project.get_data_from_api scheduled__2023-07-23T00:00:00+00:00 [running]> on host 320bc8363a40
[2023-07-24 08:28:42,576] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_final_project
AIRFLOW_CTX_TASK_ID=get_data_from_api
AIRFLOW_CTX_EXECUTION_DATE=2023-07-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-23T00:00:00+00:00
[2023-07-24 08:28:42,760] {covid_scrapper.py:13} INFO - GET DATA FROM API COMPLETED
[2023-07-24 08:28:42,771] {covid_scrapper.py:15} INFO - DATA FROM API TO DATAFRAME READY
[2023-07-24 08:28:42,811] {logging_mixin.py:115} INFO - <class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   CLOSECONTACT              145 non-null    int64 
 1   CONFIRMATION              145 non-null    int64 
 2   PROBABLE                  145 non-null    int64 
 3   SUSPECT                   145 non-null    int64 
 4   closecontact_dikarantina  145 non-null    int64 
 5   closecontact_discarded    145 non-null    int64 
 6   closecontact_meninggal    145 non-null    int64 
 7   confirmation_meninggal    145 non-null    int64 
 8   confirmation_sembuh       145 non-null    int64 
 9   kode_kab                  145 non-null    object
 10  kode_prov                 145 non-null    object
 11  nama_kab                  145 non-null    object
 12  nama_prov                 145 non-null    object
 13  probable_diisolasi        145 non-null    int64 
 14  probable_discarded        145 non-null    int64 
 15  probable_meninggal        145 non-null    int64 
 16  suspect_diisolasi         145 non-null    int64 
 17  suspect_discarded         145 non-null    int64 
 18  suspect_meninggal         145 non-null    int64 
 19  tanggal                   145 non-null    object
dtypes: int64(15), object(5)
memory usage: 22.8+ KB
[2023-07-24 08:28:42,812] {logging_mixin.py:115} INFO - None
[2023-07-24 08:28:42,825] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/d_1_final_project.py", line 27, in fun_get_data_from_api
    port=get_conn.port
  File "/opt/airflow/dags/modules/connector.py", line 10, in connect_mysql
    user, password, host, port, db
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '192.168.1.14'
[2023-07-24 08:28:42,852] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=d_1_final_project, task_id=get_data_from_api, execution_date=20230723T000000, start_date=20230724T082842, end_date=20230724T082842
[2023-07-24 08:28:42,888] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task get_data_from_api (invalid literal for int() with base 10: '192.168.1.14'; 211)
[2023-07-24 08:28:42,937] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-24 08:28:43,023] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
