[2023-07-24 14:36:55,576] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_final_project.get_data_from_api manual__2023-07-24T14:36:53.223811+00:00 [queued]>
[2023-07-24 14:36:55,594] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_final_project.get_data_from_api manual__2023-07-24T14:36:53.223811+00:00 [queued]>
[2023-07-24 14:36:55,595] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 14:36:55,595] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-24 14:36:55,596] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-24 14:36:55,623] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_from_api> on 2023-07-24 14:36:53.223811+00:00
[2023-07-24 14:36:55,632] {standard_task_runner.py:52} INFO - Started process 4519 to run task
[2023-07-24 14:36:55,638] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_final_project', 'get_data_from_api', 'manual__2023-07-24T14:36:53.223811+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/d_1_final_project.py', '--cfg-path', '/tmp/tmpjwnco2wo', '--error-file', '/tmp/tmp_g7w2onl']
[2023-07-24 14:36:55,640] {standard_task_runner.py:80} INFO - Job 18: Subtask get_data_from_api
[2023-07-24 14:36:55,766] {task_command.py:369} INFO - Running <TaskInstance: d_1_final_project.get_data_from_api manual__2023-07-24T14:36:53.223811+00:00 [running]> on host 320bc8363a40
[2023-07-24 14:36:55,936] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_final_project
AIRFLOW_CTX_TASK_ID=get_data_from_api
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T14:36:53.223811+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-24T14:36:53.223811+00:00
[2023-07-24 14:36:56,029] {covid_scrapper.py:13} INFO - GET DATA FROM API COMPLETED
[2023-07-24 14:36:56,043] {covid_scrapper.py:15} INFO - DATA FROM API TO DATAFRAME READY
[2023-07-24 14:36:56,074] {logging_mixin.py:115} INFO - <class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   CLOSECONTACT              145 non-null    int64 
 1   CONFIRMATION              145 non-null    int64 
 2   PROBABLE                  145 non-null    int64 
 3   SUSPECT                   145 non-null    int64 
 4   closecontact_dikarantina  145 non-null    int64 
 5   closecontact_discarded    145 non-null    int64 
 6   closecontact_meninggal    145 non-null    int64 
 7   confirmation_meninggal    145 non-null    int64 
 8   confirmation_sembuh       145 non-null    int64 
 9   kode_kab                  145 non-null    object
 10  kode_prov                 145 non-null    object
 11  nama_kab                  145 non-null    object
 12  nama_prov                 145 non-null    object
 13  probable_diisolasi        145 non-null    int64 
 14  probable_discarded        145 non-null    int64 
 15  probable_meninggal        145 non-null    int64 
 16  suspect_diisolasi         145 non-null    int64 
 17  suspect_discarded         145 non-null    int64 
 18  suspect_meninggal         145 non-null    int64 
 19  tanggal                   145 non-null    object
dtypes: int64(15), object(5)
memory usage: 22.8+ KB
[2023-07-24 14:36:56,076] {logging_mixin.py:115} INFO - None
[2023-07-24 14:36:56,139] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/d_1_final_project.py", line 29, in fun_get_data_from_api
    print(get_conn.info())
AttributeError: 'Connection' object has no attribute 'info'
[2023-07-24 14:36:56,221] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=d_1_final_project, task_id=get_data_from_api, execution_date=20230724T143653, start_date=20230724T143655, end_date=20230724T143656
[2023-07-24 14:36:56,298] {standard_task_runner.py:97} ERROR - Failed to execute job 18 for task get_data_from_api ('Connection' object has no attribute 'info'; 4519)
[2023-07-24 14:36:56,351] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-24 14:36:56,545] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
